---
- name: Download Jenkins repository file
  get_url:
    url: https://pkg.jenkins.io/rpm-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/rpm-stable/jenkins.io-2026.key
    state: present

- name: Install Jenkins dependencies
  dnf:
    name:
      - fontconfig
      - java-21-amazon-corretto-devel
    state: present

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes
